// File: .../orchestrator/model/SagaStatus.java
package com.example.orchestrator.model;

public enum SagaStatus {
    PENDING,
    PAYMENT_PROCESSING, PAYMENT_SUCCESS, PAYMENT_FAILED,
    INVENTORY_PROCESSING, INVENTORY_SUCCESS, INVENTORY_FAILED,
    NOTIFICATION_PROCESSING, NOTIFICATION_SUCCESS, NOTIFICATION_FAILED,
    COMPLETED,
    COMPENSATING,
    ROLLED_BACK
}